#!/usr/bin/env python3
"""core/evidence.py — Structured Immutable Evidence Graph for LONLY v2.

Enforces:
- SHA-256 content-addressable artifact hashing for every evidence node.
- Directed acyclic graph (DAG) linking findings to their source artifacts.
- Deterministic JSON serialization for verifiable audit chains.
- Provenance tagging distinguishing trusted system output from untrusted external data.
"""
from __future__ import annotations

import hashlib
import json
import os
import time
from dataclasses import dataclass, field, asdict
from enum import Enum
from typing import Optional


import uuid


class Provenance(str, Enum):
    """Provenance classification for evidence artifacts."""
    SYSTEM = "system"           # Generated by LONLY harness (trusted)
    TOOL_OUTPUT = "tool_output" # Raw subprocess output (untrusted external)
    LLM_GENERATED = "llm"      # LLM-synthesized text (untrusted internal)
    USER_INPUT = "user_input"   # Operator-provided data (semi-trusted)


@dataclass
class ExecutionContext:
    """Forensic contextual identifiers linking operations across the platform."""
    engagement_id: str = "ENG-DEFAULT"
    run_id: str = field(default_factory=lambda: f"run_{uuid.uuid4().hex[:8]}")
    task_id: str = ""
    decision_id: str = ""
    approval_id: str = ""
    execution_id: str = ""
    operator: str = "operator"


@dataclass(frozen=True)
class EvidenceNode:
    """Immutable, content-addressable evidence artifact.

    Every node carries a SHA-256 hash of its content, a provenance tag,
    forensic context IDs, and parent links forming a directed acyclic graph.
    """
    sha256: str
    content: str
    provenance: str          # Provenance enum value
    source_tool: str         # Tool that produced this artifact (or "system")
    target: str              # Target host/URL this evidence relates to
    timestamp: str           # ISO 8601
    artifact_type: str       # "raw_output", "finding", "command", "observation"
    artifact_id: str = ""    # Unique artifact ID (art_<sha256[:12]>)
    parent_hashes: tuple[str, ...] = ()  # SHA-256 refs to parent evidence nodes
    engagement_id: str = "ENG-DEFAULT"
    run_id: str = ""
    task_id: str = ""
    execution_id: str = ""
    approval_id: str = ""
    decision_id: str = ""
    operator: str = "operator"
    metadata: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        d = asdict(self)
        d["parent_hashes"] = list(self.parent_hashes)
        return d


def compute_sha256(content: str) -> str:
    """Compute SHA-256 hex digest of content string."""
    return hashlib.sha256(content.encode("utf-8", errors="replace")).hexdigest()


class EvidenceGraph:
    """Append-only directed acyclic graph of evidence artifacts.

    Nodes are content-addressed by SHA-256. Edges are parent_hashes links.
    The graph is serializable to JSON for offline audit and verification.
    """

    def __init__(
        self,
        run_dir: str | None = None,
        engagement_id: str = "ENG-DEFAULT",
        run_id: Optional[str] = None,
    ):
        self._nodes: dict[str, EvidenceNode] = {}  # sha256 -> node
        self._tool_chains: dict[str, list[str]] = {}  # tool_name -> [sha256, ...]
        self.engagement_id = engagement_id
        self.run_id = run_id or f"run_{uuid.uuid4().hex[:8]}"
        self.run_dir = run_dir or os.path.join(
            "runs", time.strftime("%Y%m%dT%H%M%S")
        )
        os.makedirs(self.run_dir, exist_ok=True)
        self.path = os.path.join(self.run_dir, "evidence_graph.json")

    def add_artifact(
        self,
        content: str,
        provenance: Provenance | str,
        source_tool: str,
        target: str = "",
        artifact_type: str = "raw_output",
        parent_hashes: tuple[str, ...] | list[str] = (),
        context: Optional[ExecutionContext] = None,
        execution_id: str = "",
        task_id: str = "",
        approval_id: str = "",
        decision_id: str = "",
        operator: str = "operator",
        metadata: dict | None = None,
    ) -> EvidenceNode:
        """Add a content-addressable evidence artifact to the graph."""
        sha = compute_sha256(content)
        prov = provenance.value if isinstance(provenance, Provenance) else str(provenance)
        ts = time.strftime("%Y-%m-%dT%H:%M:%S")
        art_id = f"art_{sha[:12]}"

        # Resolve context fields
        ctx_eng = context.engagement_id if context else self.engagement_id
        ctx_run = context.run_id if context else self.run_id
        ctx_task = context.task_id if context else task_id
        ctx_exec = context.execution_id if context else execution_id
        ctx_app = context.approval_id if context else approval_id
        ctx_dec = context.decision_id if context else decision_id
        ctx_op = context.operator if context else operator

        # Validate parent references exist in graph
        valid_parents = tuple(p for p in parent_hashes if p in self._nodes)

        node = EvidenceNode(
            sha256=sha,
            content=content,
            provenance=prov,
            source_tool=source_tool,
            target=target,
            timestamp=ts,
            artifact_type=artifact_type,
            artifact_id=art_id,
            parent_hashes=valid_parents,
            engagement_id=ctx_eng,
            run_id=ctx_run,
            task_id=ctx_task,
            execution_id=ctx_exec,
            approval_id=ctx_app,
            decision_id=ctx_dec,
            operator=ctx_op,
            metadata=metadata or {},
        )

        # Content-addressable: same content = same node (idempotent)
        if sha not in self._nodes:
            self._nodes[sha] = node
            self._tool_chains.setdefault(source_tool, []).append(sha)

        return node

    def add_command_artifact(
        self,
        executable: str,
        argv: list[str],
        target: str,
        context: Optional[ExecutionContext] = None,
        execution_id: str = "",
        task_id: str = "",
        approval_id: str = "",
    ) -> EvidenceNode:
        """Record a command invocation as an evidence artifact."""
        cmd_repr = json.dumps({"executable": executable, "argv": argv}, ensure_ascii=False)
        return self.add_artifact(
            content=cmd_repr,
            provenance=Provenance.SYSTEM,
            source_tool=executable,
            target=target,
            artifact_type="command",
            context=context,
            execution_id=execution_id,
            task_id=task_id,
            approval_id=approval_id,
        )

    def add_output_artifact(
        self,
        raw_output: str,
        source_tool: str,
        target: str,
        command_hash: str = "",
        context: Optional[ExecutionContext] = None,
        execution_id: str = "",
        task_id: str = "",
    ) -> EvidenceNode:
        """Record raw tool output with provenance tagging."""
        parents = (command_hash,) if command_hash else ()
        return self.add_artifact(
            content=raw_output,
            provenance=Provenance.TOOL_OUTPUT,
            source_tool=source_tool,
            target=target,
            artifact_type="raw_output",
            parent_hashes=parents,
            context=context,
            execution_id=execution_id,
            task_id=task_id,
        )

    def add_finding_artifact(
        self,
        finding_detail: str,
        source_tool: str,
        target: str,
        evidence_hashes: tuple[str, ...] | list[str] = (),
        severity: str = "info",
        context: Optional[ExecutionContext] = None,
        execution_id: str = "",
        task_id: str = "",
    ) -> EvidenceNode:
        """Record a confirmed finding linked to its source evidence chain."""
        return self.add_artifact(
            content=finding_detail,
            provenance=Provenance.SYSTEM,
            source_tool=source_tool,
            target=target,
            artifact_type="finding",
            parent_hashes=evidence_hashes,
            context=context,
            execution_id=execution_id,
            task_id=task_id,
            metadata={"severity": severity},
        )

    def get_provenance_trail(self, sha256: str) -> dict:
        """Return the complete forensic audit trail from finding back to operator decision."""
        if sha256 not in self._nodes:
            return {}
        chain = self.get_chain(sha256)
        root = chain[0]
        return {
            "artifact_id": root.artifact_id,
            "sha256": root.sha256,
            "artifact_type": root.artifact_type,
            "source_tool": root.source_tool,
            "target": root.target,
            "engagement_id": root.engagement_id,
            "run_id": root.run_id,
            "task_id": root.task_id,
            "execution_id": root.execution_id,
            "approval_id": root.approval_id,
            "operator": root.operator,
            "timestamp": root.timestamp,
            "chain_length": len(chain),
            "ancestor_hashes": [n.sha256 for n in chain[1:]],
        }

    def get_chain(self, sha256: str) -> list[EvidenceNode]:
        """Walk the parent chain from a node back to its roots."""
        chain = []
        visited = set()
        queue = [sha256]
        while queue:
            current = queue.pop(0)
            if current in visited or current not in self._nodes:
                continue
            visited.add(current)
            node = self._nodes[current]
            chain.append(node)
            queue.extend(node.parent_hashes)
        return chain

    def verify_node(self, sha256: str) -> bool:
        """Verify a node's content hash matches its stored SHA-256."""
        if sha256 not in self._nodes:
            return False
        node = self._nodes[sha256]
        return compute_sha256(node.content) == node.sha256

    def verify_all(self) -> tuple[int, int, list[str]]:
        """Verify all nodes in the graph. Returns (verified, total, corrupt_hashes)."""
        total = len(self._nodes)
        corrupt = []
        for sha, node in self._nodes.items():
            if compute_sha256(node.content) != sha:
                corrupt.append(sha)
        return total - len(corrupt), total, corrupt

    def get_tool_evidence(self, tool_name: str) -> list[EvidenceNode]:
        """Get all evidence nodes produced by a specific tool."""
        return [self._nodes[h] for h in self._tool_chains.get(tool_name, [])
                if h in self._nodes]

    def prompt_block(self, max_entries: int = 10) -> str:
        """Compact evidence summary for prompt injection."""
        findings = [n for n in self._nodes.values() if n.artifact_type == "finding"]
        if not findings:
            return "[EVIDENCE GRAPH] empty"
        lines = []
        for f in findings[:max_entries]:
            chain_len = len(self.get_chain(f.sha256))
            lines.append(
                f"- [{f.metadata.get('severity', 'info')}] {f.source_tool} @ {f.target}"
                f" (chain={chain_len}, sha={f.sha256[:12]}…)"
                f" — {f.content[:100]}"
            )
        return "[EVIDENCE GRAPH]\n" + "\n".join(lines)

    def save(self) -> None:
        """Persist the evidence graph to JSON."""
        data = {
            "nodes": {sha: node.to_dict() for sha, node in self._nodes.items()},
            "tool_chains": self._tool_chains,
            "metadata": {
                "total_nodes": len(self._nodes),
                "saved_at": time.strftime("%Y-%m-%dT%H:%M:%S"),
            },
        }
        with open(self.path, "w", encoding="utf-8") as fh:
            json.dump(data, fh, ensure_ascii=False, indent=2)

    @property
    def node_count(self) -> int:
        return len(self._nodes)

    @property
    def finding_count(self) -> int:
        return sum(1 for n in self._nodes.values() if n.artifact_type == "finding")


# ---------------------------------------------------------------------------
# Provenance Fencing for Untrusted Observations
# ---------------------------------------------------------------------------

def fence_untrusted(content: str, source: str = "tool_output") -> str:
    """Wrap untrusted external content in provenance fence tags.

    Mitigates indirect prompt injection by clearly delineating untrusted
    data boundaries so the LLM can distinguish system instructions from
    external observations.

    Format:
        <untrusted_observation source="tool_name" provenance="tool_output">
        ... raw content ...
        </untrusted_observation>
    """
    if not content or not isinstance(content, str):
        return content
    return (
        f'<untrusted_observation source="{source}" provenance="tool_output">\n'
        f"{content}\n"
        f"</untrusted_observation>"
    )


def strip_fences(text: str) -> str:
    """Strip provenance fence tags from text (for display/logging)."""
    import re
    return re.sub(
        r'</?untrusted_observation[^>]*>\n?',
        '',
        text,
    ).strip()


# ---------------------------------------------------------------------------
# Cryptographic Claim Verifier & Engagement Report Generator
# ---------------------------------------------------------------------------

class ClaimVerifier:
    """Verifies that statements/claims in text are backed by cryptographic evidence nodes."""

    def __init__(self, graph: EvidenceGraph):
        self.graph = graph

    def verify_final_answer(self, text: str) -> dict:
        """Scan text for claims (ports, services) and verify against evidence graph."""
        import re
        supported = []
        unsupported = []
        evidence_hashes = []

        # Extract port mentions like "port 80", "80/tcp", "port 445"
        port_matches = re.findall(r"(?:port\s+(\d+)|(\d+)/(?:tcp|udp))", text, re.IGNORECASE)
        ports_mentioned = set()
        for p1, p2 in port_matches:
            port = p1 or p2
            if port:
                ports_mentioned.add(port)

        for port in sorted(ports_mentioned):
            found_in_node = False
            for sha, node in self.graph._nodes.items():
                if port in node.content:
                    found_in_node = True
                    if sha not in evidence_hashes:
                        evidence_hashes.append(sha)
                    break
            if found_in_node:
                supported.append(f"port {port}")
            else:
                unsupported.append(f"port {port}")

        return {
            "verified": len(unsupported) == 0,
            "supported_claims": supported,
            "unsupported_claims": unsupported,
            "evidence_hashes": evidence_hashes,
        }


def generate_engagement_report(graph: EvidenceGraph, title: str = "LONLY Pentest Engagement Report") -> str:
    """Generate a cryptographic Markdown engagement report from an EvidenceGraph."""
    ts = time.strftime("%Y-%m-%d %H:%M:%S")
    verified, total, corrupt = graph.verify_all()
    
    findings = [n for n in graph._nodes.values() if n.artifact_type == "finding"]
    commands = [n for n in graph._nodes.values() if n.artifact_type == "command"]
    outputs = [n for n in graph._nodes.values() if n.artifact_type == "raw_output"]

    lines = [
        f"# {title}",
        f"**Generated:** {ts} | **Integrity Status:** {verified}/{total} verified ({'CORRUPT' if corrupt else 'OK'})",
        "",
        "## Executive Summary",
        f"- **Total Discovered Findings:** {len(findings)}",
        f"- **Commands Executed:** {len(commands)}",
        f"- **Raw Tool Observations:** {len(outputs)}",
        "",
        "## Verified Findings with Cryptographic Proof",
        "| Severity | Finding | Target | Tool | SHA-256 Proof Hash |",
        "|:---|:---|:---|:---|:---|",
    ]

    if not findings:
        lines.append("| Info | No positive findings discovered | - | - | - |")
    else:
        for f in findings:
            sev = f.metadata.get("severity", "info").upper()
            lines.append(f"| {sev} | {f.content} | `{f.target}` | `{f.source_tool}` | `{f.sha256[:16]}...` |")

    lines.extend([
        "",
        "## Cryptographic Evidence Chain (DAG)",
    ])

    for f in findings:
        chain = graph.get_chain(f.sha256)
        lines.append(f"### Finding: {f.content}")
        lines.append(f"**Hash:** `{f.sha256}`")
        for parent in chain[1:]:
            lines.append(f"- **{parent.artifact_type.upper()}** (`{parent.source_tool}`) — Hash: `{parent.sha256[:16]}...`")
        lines.append("")

    report_md = "\n".join(lines)
    if graph.run_dir:
        report_path = os.path.join(graph.run_dir, "report.md")
        try:
            with open(report_path, "w", encoding="utf-8") as fh:
                fh.write(report_md)
        except Exception:
            pass
    return report_md
