#!/usr/bin/env python3
"""core/evidence.py — Structured Immutable Evidence Graph for LONLY v2.

Enforces:
- SHA-256 content-addressable artifact hashing for every evidence node.
- Directed acyclic graph (DAG) linking findings to their source artifacts.
- Deterministic JSON serialization for verifiable audit chains.
- Provenance tagging distinguishing trusted system output from untrusted external data.
"""
from __future__ import annotations

import hashlib
import json
import os
import time
from dataclasses import dataclass, field, asdict
from enum import Enum
from typing import Optional


class Provenance(str, Enum):
    """Provenance classification for evidence artifacts."""
    SYSTEM = "system"           # Generated by LONLY harness (trusted)
    TOOL_OUTPUT = "tool_output" # Raw subprocess output (untrusted external)
    LLM_GENERATED = "llm"      # LLM-synthesized text (untrusted internal)
    USER_INPUT = "user_input"   # Operator-provided data (semi-trusted)


@dataclass(frozen=True)
class EvidenceNode:
    """Immutable, content-addressable evidence artifact.

    Every node carries a SHA-256 hash of its content, a provenance tag,
    and optional parent links forming a directed acyclic graph.
    """
    sha256: str
    content: str
    provenance: str          # Provenance enum value
    source_tool: str         # Tool that produced this artifact (or "system")
    target: str              # Target host/URL this evidence relates to
    timestamp: str           # ISO 8601
    artifact_type: str       # "raw_output", "finding", "command", "observation"
    parent_hashes: tuple[str, ...] = ()  # SHA-256 refs to parent evidence nodes
    metadata: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        d = asdict(self)
        d["parent_hashes"] = list(self.parent_hashes)
        return d


def compute_sha256(content: str) -> str:
    """Compute SHA-256 hex digest of content string."""
    return hashlib.sha256(content.encode("utf-8", errors="replace")).hexdigest()


class EvidenceGraph:
    """Append-only directed acyclic graph of evidence artifacts.

    Nodes are content-addressed by SHA-256. Edges are parent_hashes links.
    The graph is serializable to JSON for offline audit and verification.
    """

    def __init__(self, run_dir: str | None = None):
        self._nodes: dict[str, EvidenceNode] = {}  # sha256 -> node
        self._tool_chains: dict[str, list[str]] = {}  # tool_name -> [sha256, ...]
        self.run_dir = run_dir or os.path.join(
            "runs", time.strftime("%Y%m%dT%H%M%S")
        )
        os.makedirs(self.run_dir, exist_ok=True)
        self.path = os.path.join(self.run_dir, "evidence_graph.json")

    def add_artifact(
        self,
        content: str,
        provenance: Provenance | str,
        source_tool: str,
        target: str = "",
        artifact_type: str = "raw_output",
        parent_hashes: tuple[str, ...] | list[str] = (),
        metadata: dict | None = None,
    ) -> EvidenceNode:
        """Add a content-addressable evidence artifact to the graph."""
        sha = compute_sha256(content)
        prov = provenance.value if isinstance(provenance, Provenance) else str(provenance)
        ts = time.strftime("%Y-%m-%dT%H:%M:%S")

        # Validate parent references exist in graph
        valid_parents = tuple(p for p in parent_hashes if p in self._nodes)

        node = EvidenceNode(
            sha256=sha,
            content=content,
            provenance=prov,
            source_tool=source_tool,
            target=target,
            timestamp=ts,
            artifact_type=artifact_type,
            parent_hashes=valid_parents,
            metadata=metadata or {},
        )

        # Content-addressable: same content = same node (idempotent)
        if sha not in self._nodes:
            self._nodes[sha] = node
            self._tool_chains.setdefault(source_tool, []).append(sha)

        return node

    def add_command_artifact(
        self,
        executable: str,
        argv: list[str],
        target: str,
    ) -> EvidenceNode:
        """Record a command invocation as an evidence artifact."""
        cmd_repr = json.dumps({"executable": executable, "argv": argv}, ensure_ascii=False)
        return self.add_artifact(
            content=cmd_repr,
            provenance=Provenance.SYSTEM,
            source_tool=executable,
            target=target,
            artifact_type="command",
        )

    def add_output_artifact(
        self,
        raw_output: str,
        source_tool: str,
        target: str,
        command_hash: str = "",
    ) -> EvidenceNode:
        """Record raw tool output with provenance tagging."""
        parents = (command_hash,) if command_hash else ()
        return self.add_artifact(
            content=raw_output,
            provenance=Provenance.TOOL_OUTPUT,
            source_tool=source_tool,
            target=target,
            artifact_type="raw_output",
            parent_hashes=parents,
        )

    def add_finding_artifact(
        self,
        finding_detail: str,
        source_tool: str,
        target: str,
        evidence_hashes: tuple[str, ...] | list[str] = (),
        severity: str = "info",
    ) -> EvidenceNode:
        """Record a confirmed finding linked to its source evidence chain."""
        return self.add_artifact(
            content=finding_detail,
            provenance=Provenance.SYSTEM,
            source_tool=source_tool,
            target=target,
            artifact_type="finding",
            parent_hashes=evidence_hashes,
            metadata={"severity": severity},
        )

    def get_chain(self, sha256: str) -> list[EvidenceNode]:
        """Walk the parent chain from a node back to its roots."""
        chain = []
        visited = set()
        queue = [sha256]
        while queue:
            current = queue.pop(0)
            if current in visited or current not in self._nodes:
                continue
            visited.add(current)
            node = self._nodes[current]
            chain.append(node)
            queue.extend(node.parent_hashes)
        return chain

    def verify_node(self, sha256: str) -> bool:
        """Verify a node's content hash matches its stored SHA-256."""
        if sha256 not in self._nodes:
            return False
        node = self._nodes[sha256]
        return compute_sha256(node.content) == node.sha256

    def verify_all(self) -> tuple[int, int, list[str]]:
        """Verify all nodes in the graph. Returns (verified, total, corrupt_hashes)."""
        total = len(self._nodes)
        corrupt = []
        for sha, node in self._nodes.items():
            if compute_sha256(node.content) != sha:
                corrupt.append(sha)
        return total - len(corrupt), total, corrupt

    def get_tool_evidence(self, tool_name: str) -> list[EvidenceNode]:
        """Get all evidence nodes produced by a specific tool."""
        return [self._nodes[h] for h in self._tool_chains.get(tool_name, [])
                if h in self._nodes]

    def prompt_block(self, max_entries: int = 10) -> str:
        """Compact evidence summary for prompt injection."""
        findings = [n for n in self._nodes.values() if n.artifact_type == "finding"]
        if not findings:
            return "[EVIDENCE GRAPH] empty"
        lines = []
        for f in findings[:max_entries]:
            chain_len = len(self.get_chain(f.sha256))
            lines.append(
                f"- [{f.metadata.get('severity', 'info')}] {f.source_tool} @ {f.target}"
                f" (chain={chain_len}, sha={f.sha256[:12]}…)"
                f" — {f.content[:100]}"
            )
        return "[EVIDENCE GRAPH]\n" + "\n".join(lines)

    def save(self) -> None:
        """Persist the evidence graph to JSON."""
        data = {
            "nodes": {sha: node.to_dict() for sha, node in self._nodes.items()},
            "tool_chains": self._tool_chains,
            "metadata": {
                "total_nodes": len(self._nodes),
                "saved_at": time.strftime("%Y-%m-%dT%H:%M:%S"),
            },
        }
        with open(self.path, "w", encoding="utf-8") as fh:
            json.dump(data, fh, ensure_ascii=False, indent=2)

    @property
    def node_count(self) -> int:
        return len(self._nodes)

    @property
    def finding_count(self) -> int:
        return sum(1 for n in self._nodes.values() if n.artifact_type == "finding")


# ---------------------------------------------------------------------------
# Provenance Fencing for Untrusted Observations
# ---------------------------------------------------------------------------

def fence_untrusted(content: str, source: str = "tool_output") -> str:
    """Wrap untrusted external content in provenance fence tags.

    Mitigates indirect prompt injection by clearly delineating untrusted
    data boundaries so the LLM can distinguish system instructions from
    external observations.

    Format:
        <untrusted_observation source="tool_name" provenance="tool_output">
        ... raw content ...
        </untrusted_observation>
    """
    if not content or not isinstance(content, str):
        return content
    return (
        f'<untrusted_observation source="{source}" provenance="tool_output">\n'
        f"{content}\n"
        f"</untrusted_observation>"
    )


def strip_fences(text: str) -> str:
    """Strip provenance fence tags from text (for display/logging)."""
    import re
    return re.sub(
        r'</?untrusted_observation[^>]*>\n?',
        '',
        text,
    ).strip()
